### ISSUE TITLE
PHP Fatal error for "rex_path"

### ISSUE THREAD

**Issue by ghost** [mschnieder/rex4-cookie-consent#1]
Hello Markus,

We are getting an error for the Cookieconsent Plugin. We are using Redaxo 4.4.1. Could you help us? :)

`PHP Fatal error:  Class 'rex_path' not found in /****/www/redaxo/include/addons/cookieconsent/classes/class.consent.inc.php on line 22`

**Comment by skerbis** [comment]
Funktioniert erst ab 4.6 @RastaTux

**Comment by ghost** [comment]
Ah okay... Unter
https://redaxo.org/download/addons/cookieconsent/
stand: Für REDAXO 4.6.x, 4.5.x, 4.4.x, 4.3.x
;)

Läuft aber tatsächlich auch unter 4.4.x, wenn ich einfach die Zeile 22 auskommentiere.

**Comment by mschnieder** [comment]
Das Problem ist in den neueren Versionen behoben...
