### ISSUE TITLE
_blank führt zu Problem mit Firefox

### ISSUE THREAD

**Issue by skerbis** [mschnieder/rex4-cookie-consent#3]
Man kann im Firefox nicht zustimmen. Siehe https://wdfv.de 
Ich weiß nicht wo das _blank herkomnt

**Comment by mschnieder** [comment]
Hab mir es gerade mal angeschaut, bei deiner Beispielseite funktioniert es nicht, aber z.B. auf https://www.mynetworx.eu funktioniert es. Kann Sein das du andersweitig noch irgendwo nen Script hast dass diesen Parameter setzt?

**Comment by bloep** [comment]
@skerbis Schau mal in die [js/extra.js](https://wdfv.de/js/extra.js) in Zeile 556 bis 561 werden alle Links, die nicht intern sind mit einem `target="_blank"` ausgestattet.
```js
$('a').not('[href*="mailto:"]').each(function () {
        var isInternalLink = new RegExp('/' + window.location.host + '/');
        if ( ! isInternalLink.test(this.href) ) {
            $(this).attr('target', '_blank');
        }
    });
```

**Comment by bloep** [comment]
Wenn du dir nämlich den Seitenquelltext anschaust, ist der Link/Button noch ohne `target="_blank"`

**Comment by skerbis** [comment]
Danke. Shit. Danke @bloep @mschnieder. Altes Projekt kein Überblick mehr.
